[build]
builder = "nixpacks"
buildCommand = "npm ci && npm run build:prod"

[deploy]
startCommand = "nginx -g 'daemon off;'"
restartPolicyType = "on_failure"
healthcheckPath = "/health"
healthcheckTimeout = 30
healthcheckInterval = 15
restartCount = 3

[service]
internal_port = 80
port = 80

[env]
NODE_ENV = "production"