[build]
builder = "nixpacks"
buildCommand = "npm ci && npm run build:prod"

[deploy]
startCommand = "nginx -g 'daemon off;'"
healthcheckPath = "/"
healthcheckTimeout = 100

[env]
NODE_ENV = "production"