services:
  backend:
    container_name: portfolio-website-backend-dev
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_APP_PASSWORD=${EMAIL_APP_PASSWORD}
      - EMAIL_RECIPIENT=${EMAIL_RECIPIENT}
      - GOOGLE_CLOUD_KEY_FILE=${GOOGLE_CLOUD_KEY_FILE}
      - GOOGLE_CLOUD_BUCKET=${GOOGLE_CLOUD_BUCKET}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run start:dev

  frontend:
    container_name: portfolio-website-frontend-dev
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - VITE_API_URL=http://localhost:3000/api
    ports:
      - "5173:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev

networks:
  default:
    name: portfolio-dev-network
