services:
  backend:
    container_name: portfolio-website-backend-dev
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: builder # Use the builder stage for development
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/portfolio
      - JWT_SECRET=${JWT_SECRET}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_APP_PASSWORD=${EMAIL_APP_PASSWORD}
      - EMAIL_RECIPIENT=${EMAIL_RECIPIENT}
      - GOOGLE_CLOUD_KEY_FILE=${GOOGLE_CLOUD_KEY_FILE}
      - GOOGLE_CLOUD_BUCKET=${GOOGLE_CLOUD_BUCKET}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - DOCKER_HOST=unix:///var/run/docker.sock # Added for Docker-in-Docker
    ports:
      - "3000:3000"
      - "9229:9229" # Debug port
    volumes:
      - ./backend:/app
      - /app/node_modules
      - /var/run/docker.sock:/var/run/docker.sock # Added for Docker-in-Docker
    command: npm run start:dev
    depends_on:
      mongodb:
        condition: service_healthy
      three-sat-demo:
        condition: service_started
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:3000/api/health",
        ]
      interval: 10s
      timeout: 5s
      retries: 3

  frontend:
    container_name: portfolio-website-frontend-dev
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: builder # Use builder stage for development
    environment:
      - VITE_API_URL=http://localhost:3000/api
    ports:
      - "5173:5173" # Vite's default dev port
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host
    depends_on:
      - backend
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:5173",
        ]
      interval: 10s
      timeout: 3s
      retries: 3

  mongodb:
    image: mongo:latest
    container_name: portfolio-mongodb-dev
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  three-sat-demo:
    build:
      context: ./backend/src/demos/docker/three-sat-demo
      dockerfile: Dockerfile
    container_name: portfolio-website-three-sat-demo
    image: portfolio-website-three-sat-demo # Added explicit image name
    restart: "no"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:size=64M
    stop_grace_period: 65s
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.exit(0)"]
      interval: 30s
      timeout: 3s
      retries: 3

volumes:
  mongodb_data:

networks:
  default:
    name: portfolio-dev-network
